apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mguirola201700772-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-mguirola201700772-container
          image: miguelguirola/mguirola201700772-api
          ports:
            - containerPort: 4000