apiVersion: v1
kind: Service
metadata:
  name: api-mguirola201700772-service
  namespace: default
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000        # Puerto donde se expone el servicio
      targetPort: 4000  # Puerto al que apunta el servicio en los pods
      nodePort: 30400   # Puerto donde se expone el servicio en el nodo
  type: NodePort