apiVersion: v1
kind: Service
metadata:
  name: front-mguirola201700772-service
  namespace: default
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3000        # Puerto donde se expone el servicio
      targetPort: 3000  # Puerto al que apunta el servicio en los pods
      nodePort: 30300   # Puerto del nodo donde se expone el servicio
  type: NodePort        # Tipo de servicio
