apiVersion: v1
kind: Service
metadata:
  name: mysql-mguirola201700772-service
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Puerto expuesto por el servicio
      targetPort: 3306  # Puerto expuesto por el contenedor
      nodePort: 30330   # Puerto expuesto por el nodo
  type: NodePort        # Tipo de servicio expuesto